-- Fiscara database schema for Supabase.
-- Run this entire file once in Supabase > SQL Editor > New query.

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  institution text not null default 'Manual',
  type text not null,
  currency text not null default 'EUR',
  current_balance numeric(14,2) not null default 0,
  last_four text,
  color text not null default '#42efb1',
  created_at timestamptz not null default now()
);

create table if not exists public.budget_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month_key text not null,
  monthly_target numeric(14,2) not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, month_key)
);

create table if not exists public.budget_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month_key text not null,
  name text not null,
  category text not null,
  amount numeric(14,2) not null,
  kind text not null default 'expense' check (kind in ('expense', 'income')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  name text not null,
  category text not null,
  amount numeric(14,2) not null,
  kind text not null check (kind in ('expense', 'income')),
  transaction_date date not null,
  source text not null default 'manual',
  fingerprint text,
  original_description text,
  created_at timestamptz not null default now()
);

create table if not exists public.savings_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_amount numeric(14,2) not null,
  current_amount numeric(14,2) not null default 0,
  target_date date,
  color text not null default '#42efb1',
  created_at timestamptz not null default now()
);

create index if not exists accounts_user_idx on public.accounts(user_id);
create index if not exists budget_items_user_month_idx on public.budget_items(user_id, month_key);
create index if not exists transactions_user_idx on public.transactions(user_id);
create index if not exists transactions_account_idx on public.transactions(account_id);
create unique index if not exists transactions_user_fingerprint_uidx
  on public.transactions(user_id, fingerprint) where fingerprint is not null;
create index if not exists savings_goals_user_idx on public.savings_goals(user_id);

alter table public.accounts enable row level security;
alter table public.budget_settings enable row level security;
alter table public.budget_items enable row level security;
alter table public.transactions enable row level security;
alter table public.savings_goals enable row level security;

grant select, insert, update, delete on public.accounts to authenticated;
grant select, insert, update, delete on public.budget_settings to authenticated;
grant select, insert, update, delete on public.budget_items to authenticated;
grant select, insert, update, delete on public.transactions to authenticated;
grant select, insert, update, delete on public.savings_goals to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Users manage own accounts" on public.accounts;
create policy "Users manage own accounts" on public.accounts
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own budget settings" on public.budget_settings;
create policy "Users manage own budget settings" on public.budget_settings
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own budget items" on public.budget_items;
create policy "Users manage own budget items" on public.budget_items
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own transactions" on public.transactions;
create policy "Users manage own transactions" on public.transactions
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own savings goals" on public.savings_goals;
create policy "Users manage own savings goals" on public.savings_goals
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
